/* Automatically @generated by tree-sitter */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 15
#define STATE_COUNT 12
#define LARGE_STATE_COUNT 8
#define SYMBOL_COUNT 26
#define ALIAS_COUNT 0
#define TOKEN_COUNT 21
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 2
#define MAX_ALIAS_SEQUENCE_LENGTH 4
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 3
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  sym_meta_keyword = 1,
  sym_meta_platform_value = 2,
  sym_meta_value = 3,
  sym_at_command = 4,
  sym_instrument_type = 5,
  sym_note = 6,
  sym_rest = 7,
  sym_command_with_number = 8,
  sym_command = 9,
  sym_escape_command = 10,
  anon_sym_SQUOTE = 11,
  aux_sym_platform_command_token1 = 12,
  sym_platform_command_keyword = 13,
  sym_number = 14,
  sym_string = 15,
  sym_track_selector = 16,
  sym_operator = 17,
  sym_punctuation = 18,
  sym_param_key = 19,
  sym_comment = 20,
  sym_source_file = 21,
  sym__item = 22,
  sym_meta_command = 23,
  sym_platform_command = 24,
  aux_sym_source_file_repeat1 = 25,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [sym_meta_keyword] = "meta_keyword",
  [sym_meta_platform_value] = "meta_platform_value",
  [sym_meta_value] = "meta_value",
  [sym_at_command] = "at_command",
  [sym_instrument_type] = "instrument_type",
  [sym_note] = "note",
  [sym_rest] = "rest",
  [sym_command_with_number] = "command_with_number",
  [sym_command] = "command",
  [sym_escape_command] = "escape_command",
  [anon_sym_SQUOTE] = "'",
  [aux_sym_platform_command_token1] = "platform_command_token1",
  [sym_platform_command_keyword] = "platform_command_keyword",
  [sym_number] = "number",
  [sym_string] = "string",
  [sym_track_selector] = "track_selector",
  [sym_operator] = "operator",
  [sym_punctuation] = "punctuation",
  [sym_param_key] = "param_key",
  [sym_comment] = "comment",
  [sym_source_file] = "source_file",
  [sym__item] = "_item",
  [sym_meta_command] = "meta_command",
  [sym_platform_command] = "platform_command",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [sym_meta_keyword] = sym_meta_keyword,
  [sym_meta_platform_value] = sym_meta_platform_value,
  [sym_meta_value] = sym_meta_value,
  [sym_at_command] = sym_at_command,
  [sym_instrument_type] = sym_instrument_type,
  [sym_note] = sym_note,
  [sym_rest] = sym_rest,
  [sym_command_with_number] = sym_command_with_number,
  [sym_command] = sym_command,
  [sym_escape_command] = sym_escape_command,
  [anon_sym_SQUOTE] = anon_sym_SQUOTE,
  [aux_sym_platform_command_token1] = aux_sym_platform_command_token1,
  [sym_platform_command_keyword] = sym_platform_command_keyword,
  [sym_number] = sym_number,
  [sym_string] = sym_string,
  [sym_track_selector] = sym_track_selector,
  [sym_operator] = sym_operator,
  [sym_punctuation] = sym_punctuation,
  [sym_param_key] = sym_param_key,
  [sym_comment] = sym_comment,
  [sym_source_file] = sym_source_file,
  [sym__item] = sym__item,
  [sym_meta_command] = sym_meta_command,
  [sym_platform_command] = sym_platform_command,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [sym_meta_keyword] = {
    .visible = true,
    .named = true,
  },
  [sym_meta_platform_value] = {
    .visible = true,
    .named = true,
  },
  [sym_meta_value] = {
    .visible = true,
    .named = true,
  },
  [sym_at_command] = {
    .visible = true,
    .named = true,
  },
  [sym_instrument_type] = {
    .visible = true,
    .named = true,
  },
  [sym_note] = {
    .visible = true,
    .named = true,
  },
  [sym_rest] = {
    .visible = true,
    .named = true,
  },
  [sym_command_with_number] = {
    .visible = true,
    .named = true,
  },
  [sym_command] = {
    .visible = true,
    .named = true,
  },
  [sym_escape_command] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_SQUOTE] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_platform_command_token1] = {
    .visible = false,
    .named = false,
  },
  [sym_platform_command_keyword] = {
    .visible = true,
    .named = true,
  },
  [sym_number] = {
    .visible = true,
    .named = true,
  },
  [sym_string] = {
    .visible = true,
    .named = true,
  },
  [sym_track_selector] = {
    .visible = true,
    .named = true,
  },
  [sym_operator] = {
    .visible = true,
    .named = true,
  },
  [sym_punctuation] = {
    .visible = true,
    .named = true,
  },
  [sym_param_key] = {
    .visible = true,
    .named = true,
  },
  [sym_comment] = {
    .visible = true,
    .named = true,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym__item] = {
    .visible = false,
    .named = true,
  },
  [sym_meta_command] = {
    .visible = true,
    .named = true,
  },
  [sym_platform_command] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
};

enum ts_field_identifiers {
  field_args = 1,
  field_keyword = 2,
};

static const char * const ts_field_names[] = {
  [0] = NULL,
  [field_args] = "args",
  [field_keyword] = "keyword",
};

static const TSMapSlice ts_field_map_slices[PRODUCTION_ID_COUNT] = {
  [1] = {.index = 0, .length = 1},
  [2] = {.index = 1, .length = 2},
};

static const TSFieldMapEntry ts_field_map_entries[] = {
  [0] =
    {field_keyword, 1},
  [1] =
    {field_args, 2},
    {field_keyword, 1},
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(38);
      ADVANCE_MAP(
        '"', 1,
        '#', 6,
        '\'', 186,
        '*', 202,
        '2', 193,
        ';', 205,
        '@', 32,
        '\\', 185,
        '_', 180,
        'f', 172,
        'o', 182,
        'p', 181,
        'r', 175,
        '&', 178,
        '^', 178,
        '+', 201,
        '-', 201,
        'k', 183,
        'l', 183,
        'q', 183,
        's', 183,
        't', 183,
        'v', 183,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(129);
      if ((',' <= lookahead && lookahead <= '.') ||
          ('[' <= lookahead && lookahead <= ']') ||
          ('{' <= lookahead && lookahead <= '}')) ADVANCE(203);
      if (('(' <= lookahead && lookahead <= '/') ||
          (':' <= lookahead && lookahead <= '>')) ADVANCE(200);
      if (('a' <= lookahead && lookahead <= 'h')) ADVANCE(173);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(194);
      if (('C' <= lookahead && lookahead <= 'E') ||
          lookahead == 'G' ||
          lookahead == 'K' ||
          lookahead == 'M' ||
          ('P' <= lookahead && lookahead <= 'R') ||
          lookahead == 'T' ||
          lookahead == 'V') ADVANCE(197);
      if (('A' <= lookahead && lookahead <= 'Z')) ADVANCE(199);
      END_STATE();
    case 1:
      if (lookahead == '"') ADVANCE(196);
      if (lookahead == '\\') ADVANCE(36);
      if (lookahead != 0) ADVANCE(1);
      END_STATE();
    case 2:
      if (lookahead == '\'') ADVANCE(186);
      if (lookahead == ';') ADVANCE(188);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(189);
      if (lookahead != 0) ADVANCE(190);
      END_STATE();
    case 3:
      if (lookahead == '3') ADVANCE(191);
      END_STATE();
    case 4:
      if (lookahead == ';') ADVANCE(205);
      if (lookahead == 'f') ADVANCE(20);
      if (lookahead == 'l') ADVANCE(14);
      if (lookahead == 'm') ADVANCE(22);
      if (lookahead == 'p') ADVANCE(8);
      if (lookahead == 't') ADVANCE(17);
      if (lookahead == 'w') ADVANCE(25);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(4);
      END_STATE();
    case 5:
      if (lookahead == '_') ADVANCE(5);
      if (lookahead == '+' ||
          lookahead == '-') ADVANCE(33);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(176);
      END_STATE();
    case 6:
      if (lookahead == 'a') ADVANCE(123);
      if (lookahead == 'c') ADVANCE(87);
      if (lookahead == 'd') ADVANCE(39);
      if (lookahead == 'g') ADVANCE(40);
      if (lookahead == 'o') ADVANCE(99);
      if (lookahead == 'p') ADVANCE(69);
      if (lookahead == 't') ADVANCE(61);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('b' <= lookahead && lookahead <= 'z')) ADVANCE(125);
      END_STATE();
    case 7:
      if (lookahead == 'a') ADVANCE(29);
      END_STATE();
    case 8:
      if (lookahead == 'c') ADVANCE(21);
      END_STATE();
    case 9:
      if (lookahead == 'd') ADVANCE(11);
      END_STATE();
    case 10:
      if (lookahead == 'e') ADVANCE(204);
      END_STATE();
    case 11:
      if (lookahead == 'e') ADVANCE(191);
      END_STATE();
    case 12:
      if (lookahead == 'e') ADVANCE(28);
      END_STATE();
    case 13:
      if (lookahead == 'f') ADVANCE(26);
      END_STATE();
    case 14:
      if (lookahead == 'f') ADVANCE(23);
      END_STATE();
    case 15:
      if (lookahead == 'g') ADVANCE(171);
      END_STATE();
    case 16:
      if (lookahead == 'i') ADVANCE(29);
      END_STATE();
    case 17:
      if (lookahead == 'l') ADVANCE(30);
      END_STATE();
    case 18:
      if (lookahead == 'm') ADVANCE(171);
      END_STATE();
    case 19:
      if (lookahead == 'm') ADVANCE(22);
      if (lookahead == 'r') ADVANCE(7);
      END_STATE();
    case 20:
      if (lookahead == 'm') ADVANCE(3);
      END_STATE();
    case 21:
      if (lookahead == 'm') ADVANCE(19);
      END_STATE();
    case 22:
      if (lookahead == 'o') ADVANCE(9);
      END_STATE();
    case 23:
      if (lookahead == 'o') ADVANCE(192);
      END_STATE();
    case 24:
      if (lookahead == 'p') ADVANCE(171);
      END_STATE();
    case 25:
      if (lookahead == 'r') ADVANCE(16);
      END_STATE();
    case 26:
      if (lookahead == 's') ADVANCE(12);
      END_STATE();
    case 27:
      if (lookahead == 't') ADVANCE(10);
      END_STATE();
    case 28:
      if (lookahead == 't') ADVANCE(204);
      END_STATE();
    case 29:
      if (lookahead == 't') ADVANCE(11);
      END_STATE();
    case 30:
      if (('1' <= lookahead && lookahead <= '4')) ADVANCE(191);
      END_STATE();
    case 31:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(170);
      END_STATE();
    case 32:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(170);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(31);
      END_STATE();
    case 33:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(176);
      END_STATE();
    case 34:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(195);
      END_STATE();
    case 35:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(177);
      END_STATE();
    case 36:
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(1);
      END_STATE();
    case 37:
      if (eof) ADVANCE(38);
      ADVANCE_MAP(
        '"', 1,
        '#', 6,
        '\'', 186,
        '*', 202,
        '2', 193,
        ';', 205,
        '@', 32,
        '\\', 185,
        '_', 180,
        'f', 172,
        'o', 182,
        'p', 181,
        'r', 175,
        '&', 178,
        '^', 178,
        '+', 201,
        '-', 201,
        'k', 183,
        'l', 183,
        'q', 183,
        's', 183,
        't', 183,
        'v', 183,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(37);
      if ((',' <= lookahead && lookahead <= '.') ||
          ('[' <= lookahead && lookahead <= ']') ||
          ('{' <= lookahead && lookahead <= '}')) ADVANCE(203);
      if (('(' <= lookahead && lookahead <= '/') ||
          (':' <= lookahead && lookahead <= '>')) ADVANCE(200);
      if (('a' <= lookahead && lookahead <= 'h')) ADVANCE(173);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(194);
      if (('C' <= lookahead && lookahead <= 'E') ||
          lookahead == 'G' ||
          lookahead == 'K' ||
          lookahead == 'M' ||
          ('P' <= lookahead && lookahead <= 'R') ||
          lookahead == 'T' ||
          lookahead == 'V') ADVANCE(197);
      if (('A' <= lookahead && lookahead <= 'Z')) ADVANCE(199);
      END_STATE();
    case 38:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 39:
      ACCEPT_TOKEN(sym_meta_keyword);
      if (lookahead == 'a') ADVANCE(114);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('b' <= lookahead && lookahead <= 'z')) ADVANCE(125);
      END_STATE();
    case 40:
      ACCEPT_TOKEN(sym_meta_keyword);
      if (lookahead == 'a') ADVANCE(74);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('b' <= lookahead && lookahead <= 'z')) ADVANCE(125);
      END_STATE();
    case 41:
      ACCEPT_TOKEN(sym_meta_keyword);
      if (lookahead == 'a') ADVANCE(118);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('b' <= lookahead && lookahead <= 'z')) ADVANCE(126);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(169);
      END_STATE();
    case 42:
      ACCEPT_TOKEN(sym_meta_keyword);
      if (lookahead == 'a') ADVANCE(76);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('b' <= lookahead && lookahead <= 'z')) ADVANCE(126);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(169);
      END_STATE();
    case 43:
      ACCEPT_TOKEN(sym_meta_keyword);
      if (lookahead == 'a') ADVANCE(81);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('b' <= lookahead && lookahead <= 'z')) ADVANCE(125);
      END_STATE();
    case 44:
      ACCEPT_TOKEN(sym_meta_keyword);
      if (lookahead == 'a') ADVANCE(82);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('b' <= lookahead && lookahead <= 'z')) ADVANCE(126);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(169);
      END_STATE();
    case 45:
      ACCEPT_TOKEN(sym_meta_keyword);
      if (lookahead == 'a') ADVANCE(116);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('b' <= lookahead && lookahead <= 'z')) ADVANCE(125);
      END_STATE();
    case 46:
      ACCEPT_TOKEN(sym_meta_keyword);
      if (lookahead == 'a') ADVANCE(120);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('b' <= lookahead && lookahead <= 'z')) ADVANCE(126);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(169);
      END_STATE();
    case 47:
      ACCEPT_TOKEN(sym_meta_keyword);
      if (lookahead == 'e') ADVANCE(125);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(125);
      END_STATE();
    case 48:
      ACCEPT_TOKEN(sym_meta_keyword);
      if (lookahead == 'e') ADVANCE(126);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(126);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(169);
      END_STATE();
    case 49:
      ACCEPT_TOKEN(sym_meta_keyword);
      if (lookahead == 'e') ADVANCE(85);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(125);
      END_STATE();
    case 50:
      ACCEPT_TOKEN(sym_meta_keyword);
      if (lookahead == 'e') ADVANCE(86);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(126);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(169);
      END_STATE();
    case 51:
      ACCEPT_TOKEN(sym_meta_keyword);
      if (lookahead == 'e') ADVANCE(101);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(125);
      END_STATE();
    case 52:
      ACCEPT_TOKEN(sym_meta_keyword);
      if (lookahead == 'e') ADVANCE(102);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(126);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(169);
      END_STATE();
    case 53:
      ACCEPT_TOKEN(sym_meta_keyword);
      if (lookahead == 'e') ADVANCE(103);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(125);
      END_STATE();
    case 54:
      ACCEPT_TOKEN(sym_meta_keyword);
      if (lookahead == 'e') ADVANCE(104);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(126);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(169);
      END_STATE();
    case 55:
      ACCEPT_TOKEN(sym_meta_keyword);
      if (lookahead == 'f') ADVANCE(97);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(125);
      END_STATE();
    case 56:
      ACCEPT_TOKEN(sym_meta_keyword);
      if (lookahead == 'f') ADVANCE(98);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(126);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(169);
      END_STATE();
    case 57:
      ACCEPT_TOKEN(sym_meta_keyword);
      if (lookahead == 'g') ADVANCE(107);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(125);
      END_STATE();
    case 58:
      ACCEPT_TOKEN(sym_meta_keyword);
      if (lookahead == 'g') ADVANCE(108);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(126);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(169);
      END_STATE();
    case 59:
      ACCEPT_TOKEN(sym_meta_keyword);
      if (lookahead == 'h') ADVANCE(93);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(125);
      END_STATE();
    case 60:
      ACCEPT_TOKEN(sym_meta_keyword);
      if (lookahead == 'h') ADVANCE(95);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(126);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(169);
      END_STATE();
    case 61:
      ACCEPT_TOKEN(sym_meta_keyword);
      if (lookahead == 'i') ADVANCE(115);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(125);
      END_STATE();
    case 62:
      ACCEPT_TOKEN(sym_meta_keyword);
      if (lookahead == 'i') ADVANCE(119);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(126);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(169);
      END_STATE();
    case 63:
      ACCEPT_TOKEN(sym_meta_keyword);
      if (lookahead == 'i') ADVANCE(94);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(125);
      END_STATE();
    case 64:
      ACCEPT_TOKEN(sym_meta_keyword);
      if (lookahead == 'i') ADVANCE(96);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(126);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(169);
      END_STATE();
    case 65:
      ACCEPT_TOKEN(sym_meta_keyword);
      if (lookahead == 'j') ADVANCE(125);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(125);
      END_STATE();
    case 66:
      ACCEPT_TOKEN(sym_meta_keyword);
      if (lookahead == 'j') ADVANCE(126);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(126);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(169);
      END_STATE();
    case 67:
      ACCEPT_TOKEN(sym_meta_keyword);
      if (lookahead == 'l') ADVANCE(47);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(125);
      END_STATE();
    case 68:
      ACCEPT_TOKEN(sym_meta_keyword);
      if (lookahead == 'l') ADVANCE(48);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(126);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(169);
      END_STATE();
    case 69:
      ACCEPT_TOKEN(sym_meta_keyword);
      if (lookahead == 'l') ADVANCE(45);
      if (lookahead == 'r') ADVANCE(88);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(125);
      END_STATE();
    case 70:
      ACCEPT_TOKEN(sym_meta_keyword);
      if (lookahead == 'l') ADVANCE(46);
      if (lookahead == 'r') ADVANCE(90);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(126);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(169);
      END_STATE();
    case 71:
      ACCEPT_TOKEN(sym_meta_keyword);
      if (lookahead == 'm') ADVANCE(125);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(125);
      END_STATE();
    case 72:
      ACCEPT_TOKEN(sym_meta_keyword);
      if (lookahead == 'm') ADVANCE(126);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(126);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(169);
      END_STATE();
    case 73:
      ACCEPT_TOKEN(sym_meta_keyword);
      if (lookahead == 'm') ADVANCE(77);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(125);
      END_STATE();
    case 74:
      ACCEPT_TOKEN(sym_meta_keyword);
      if (lookahead == 'm') ADVANCE(47);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(125);
      END_STATE();
    case 75:
      ACCEPT_TOKEN(sym_meta_keyword);
      if (lookahead == 'm') ADVANCE(78);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(126);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(169);
      END_STATE();
    case 76:
      ACCEPT_TOKEN(sym_meta_keyword);
      if (lookahead == 'm') ADVANCE(48);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(126);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(169);
      END_STATE();
    case 77:
      ACCEPT_TOKEN(sym_meta_keyword);
      if (lookahead == 'm') ADVANCE(49);
      if (lookahead == 'p') ADVANCE(91);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(125);
      END_STATE();
    case 78:
      ACCEPT_TOKEN(sym_meta_keyword);
      if (lookahead == 'm') ADVANCE(50);
      if (lookahead == 'p') ADVANCE(92);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(126);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(169);
      END_STATE();
    case 79:
      ACCEPT_TOKEN(sym_meta_keyword);
      if (lookahead == 'm') ADVANCE(51);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(125);
      END_STATE();
    case 80:
      ACCEPT_TOKEN(sym_meta_keyword);
      if (lookahead == 'm') ADVANCE(52);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(126);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(169);
      END_STATE();
    case 81:
      ACCEPT_TOKEN(sym_meta_keyword);
      if (lookahead == 'm') ADVANCE(79);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(125);
      END_STATE();
    case 82:
      ACCEPT_TOKEN(sym_meta_keyword);
      if (lookahead == 'm') ADVANCE(80);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(126);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(169);
      END_STATE();
    case 83:
      ACCEPT_TOKEN(sym_meta_keyword);
      if (lookahead == 'n') ADVANCE(125);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(125);
      END_STATE();
    case 84:
      ACCEPT_TOKEN(sym_meta_keyword);
      if (lookahead == 'n') ADVANCE(126);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(126);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(169);
      END_STATE();
    case 85:
      ACCEPT_TOKEN(sym_meta_keyword);
      if (lookahead == 'n') ADVANCE(111);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(125);
      END_STATE();
    case 86:
      ACCEPT_TOKEN(sym_meta_keyword);
      if (lookahead == 'n') ADVANCE(112);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(126);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(169);
      END_STATE();
    case 87:
      ACCEPT_TOKEN(sym_meta_keyword);
      if (lookahead == 'o') ADVANCE(73);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(125);
      END_STATE();
    case 88:
      ACCEPT_TOKEN(sym_meta_keyword);
      if (lookahead == 'o') ADVANCE(57);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(125);
      END_STATE();
    case 89:
      ACCEPT_TOKEN(sym_meta_keyword);
      if (lookahead == 'o') ADVANCE(75);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(126);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(169);
      END_STATE();
    case 90:
      ACCEPT_TOKEN(sym_meta_keyword);
      if (lookahead == 'o') ADVANCE(58);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(126);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(169);
      END_STATE();
    case 91:
      ACCEPT_TOKEN(sym_meta_keyword);
      if (lookahead == 'o') ADVANCE(109);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(125);
      END_STATE();
    case 92:
      ACCEPT_TOKEN(sym_meta_keyword);
      if (lookahead == 'o') ADVANCE(110);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(126);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(169);
      END_STATE();
    case 93:
      ACCEPT_TOKEN(sym_meta_keyword);
      if (lookahead == 'o') ADVANCE(101);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(125);
      END_STATE();
    case 94:
      ACCEPT_TOKEN(sym_meta_keyword);
      if (lookahead == 'o') ADVANCE(83);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(125);
      END_STATE();
    case 95:
      ACCEPT_TOKEN(sym_meta_keyword);
      if (lookahead == 'o') ADVANCE(102);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(126);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(169);
      END_STATE();
    case 96:
      ACCEPT_TOKEN(sym_meta_keyword);
      if (lookahead == 'o') ADVANCE(84);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(126);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(169);
      END_STATE();
    case 97:
      ACCEPT_TOKEN(sym_meta_keyword);
      if (lookahead == 'o') ADVANCE(105);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(125);
      END_STATE();
    case 98:
      ACCEPT_TOKEN(sym_meta_keyword);
      if (lookahead == 'o') ADVANCE(106);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(126);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(169);
      END_STATE();
    case 99:
      ACCEPT_TOKEN(sym_meta_keyword);
      if (lookahead == 'p') ADVANCE(121);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(125);
      END_STATE();
    case 100:
      ACCEPT_TOKEN(sym_meta_keyword);
      if (lookahead == 'p') ADVANCE(122);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(126);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(169);
      END_STATE();
    case 101:
      ACCEPT_TOKEN(sym_meta_keyword);
      if (lookahead == 'r') ADVANCE(125);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(125);
      END_STATE();
    case 102:
      ACCEPT_TOKEN(sym_meta_keyword);
      if (lookahead == 'r') ADVANCE(126);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(126);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(169);
      END_STATE();
    case 103:
      ACCEPT_TOKEN(sym_meta_keyword);
      if (lookahead == 'r') ADVANCE(65);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(125);
      END_STATE();
    case 104:
      ACCEPT_TOKEN(sym_meta_keyword);
      if (lookahead == 'r') ADVANCE(66);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(126);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(169);
      END_STATE();
    case 105:
      ACCEPT_TOKEN(sym_meta_keyword);
      if (lookahead == 'r') ADVANCE(71);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(125);
      END_STATE();
    case 106:
      ACCEPT_TOKEN(sym_meta_keyword);
      if (lookahead == 'r') ADVANCE(72);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(126);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(169);
      END_STATE();
    case 107:
      ACCEPT_TOKEN(sym_meta_keyword);
      if (lookahead == 'r') ADVANCE(43);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(125);
      END_STATE();
    case 108:
      ACCEPT_TOKEN(sym_meta_keyword);
      if (lookahead == 'r') ADVANCE(44);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(126);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(169);
      END_STATE();
    case 109:
      ACCEPT_TOKEN(sym_meta_keyword);
      if (lookahead == 's') ADVANCE(53);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(125);
      END_STATE();
    case 110:
      ACCEPT_TOKEN(sym_meta_keyword);
      if (lookahead == 's') ADVANCE(54);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(126);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(169);
      END_STATE();
    case 111:
      ACCEPT_TOKEN(sym_meta_keyword);
      if (lookahead == 't') ADVANCE(125);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(125);
      END_STATE();
    case 112:
      ACCEPT_TOKEN(sym_meta_keyword);
      if (lookahead == 't') ADVANCE(126);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(126);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(169);
      END_STATE();
    case 113:
      ACCEPT_TOKEN(sym_meta_keyword);
      if (lookahead == 't') ADVANCE(59);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(125);
      END_STATE();
    case 114:
      ACCEPT_TOKEN(sym_meta_keyword);
      if (lookahead == 't') ADVANCE(47);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(125);
      END_STATE();
    case 115:
      ACCEPT_TOKEN(sym_meta_keyword);
      if (lookahead == 't') ADVANCE(67);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(125);
      END_STATE();
    case 116:
      ACCEPT_TOKEN(sym_meta_keyword);
      if (lookahead == 't') ADVANCE(55);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(125);
      END_STATE();
    case 117:
      ACCEPT_TOKEN(sym_meta_keyword);
      if (lookahead == 't') ADVANCE(60);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(126);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(169);
      END_STATE();
    case 118:
      ACCEPT_TOKEN(sym_meta_keyword);
      if (lookahead == 't') ADVANCE(48);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(126);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(169);
      END_STATE();
    case 119:
      ACCEPT_TOKEN(sym_meta_keyword);
      if (lookahead == 't') ADVANCE(68);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(126);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(169);
      END_STATE();
    case 120:
      ACCEPT_TOKEN(sym_meta_keyword);
      if (lookahead == 't') ADVANCE(56);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(126);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(169);
      END_STATE();
    case 121:
      ACCEPT_TOKEN(sym_meta_keyword);
      if (lookahead == 't') ADVANCE(63);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(125);
      END_STATE();
    case 122:
      ACCEPT_TOKEN(sym_meta_keyword);
      if (lookahead == 't') ADVANCE(64);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(126);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(169);
      END_STATE();
    case 123:
      ACCEPT_TOKEN(sym_meta_keyword);
      if (lookahead == 'u') ADVANCE(113);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(125);
      END_STATE();
    case 124:
      ACCEPT_TOKEN(sym_meta_keyword);
      if (lookahead == 'u') ADVANCE(117);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(126);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(169);
      END_STATE();
    case 125:
      ACCEPT_TOKEN(sym_meta_keyword);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(125);
      END_STATE();
    case 126:
      ACCEPT_TOKEN(sym_meta_keyword);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(126);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(169);
      END_STATE();
    case 127:
      ACCEPT_TOKEN(sym_meta_platform_value);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(127);
      END_STATE();
    case 128:
      ACCEPT_TOKEN(sym_meta_value);
      if (lookahead == '\n') ADVANCE(1);
      if (lookahead == '"') ADVANCE(169);
      if (lookahead == '\\') ADVANCE(168);
      if (lookahead != 0) ADVANCE(128);
      END_STATE();
    case 129:
      ACCEPT_TOKEN(sym_meta_value);
      ADVANCE_MAP(
        '\n', 129,
        '"', 128,
        '#', 134,
        '\'', 187,
        '*', 165,
        '2', 130,
        ';', 169,
        '@', 164,
        '\\', 132,
        '_', 133,
        'f', 149,
        'm', 138,
        'o', 144,
        'p', 137,
        'r', 135,
        '&', 169,
        '^', 169,
        '+', 166,
        '-', 166,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(129);
      if (lookahead == 'k' ||
          lookahead == 'l' ||
          ('q' <= lookahead && lookahead <= 't') ||
          lookahead == 'v') ADVANCE(161);
      if ((',' <= lookahead && lookahead <= '.') ||
          ('[' <= lookahead && lookahead <= ']') ||
          ('{' <= lookahead && lookahead <= '}')) ADVANCE(169);
      if (('(' <= lookahead && lookahead <= '/') ||
          (':' <= lookahead && lookahead <= '>')) ADVANCE(169);
      if (('a' <= lookahead && lookahead <= 'h')) ADVANCE(162);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(131);
      if (('C' <= lookahead && lookahead <= 'E') ||
          lookahead == 'G' ||
          lookahead == 'K' ||
          lookahead == 'M' ||
          ('P' <= lookahead && lookahead <= 'R') ||
          lookahead == 'T' ||
          lookahead == 'V') ADVANCE(160);
      if (('A' <= lookahead && lookahead <= 'Z')) ADVANCE(167);
      if (lookahead != 0) ADVANCE(169);
      END_STATE();
    case 130:
      ACCEPT_TOKEN(sym_meta_value);
      if (lookahead == '.') ADVANCE(165);
      if (lookahead == 'o') ADVANCE(151);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(131);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(169);
      END_STATE();
    case 131:
      ACCEPT_TOKEN(sym_meta_value);
      if (lookahead == '.') ADVANCE(165);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(131);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(169);
      END_STATE();
    case 132:
      ACCEPT_TOKEN(sym_meta_value);
      if (lookahead == '=') ADVANCE(169);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(169);
      END_STATE();
    case 133:
      ACCEPT_TOKEN(sym_meta_value);
      if (lookahead == '_') ADVANCE(133);
      if (lookahead == '+' ||
          lookahead == '-') ADVANCE(166);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(131);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(169);
      END_STATE();
    case 134:
      ACCEPT_TOKEN(sym_meta_value);
      if (lookahead == 'a') ADVANCE(124);
      if (lookahead == 'c') ADVANCE(89);
      if (lookahead == 'd') ADVANCE(41);
      if (lookahead == 'g') ADVANCE(42);
      if (lookahead == 'o') ADVANCE(100);
      if (lookahead == 'p') ADVANCE(70);
      if (lookahead == 't') ADVANCE(62);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('b' <= lookahead && lookahead <= 'z')) ADVANCE(126);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(169);
      END_STATE();
    case 135:
      ACCEPT_TOKEN(sym_meta_value);
      if (lookahead == 'a') ADVANCE(157);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(169);
      END_STATE();
    case 136:
      ACCEPT_TOKEN(sym_meta_value);
      if (lookahead == 'a') ADVANCE(140);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(169);
      END_STATE();
    case 137:
      ACCEPT_TOKEN(sym_meta_value);
      if (lookahead == 'c') ADVANCE(150);
      if (lookahead == 's') ADVANCE(146);
      if (lookahead == '+' ||
          lookahead == '-') ADVANCE(166);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(131);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(169);
      END_STATE();
    case 138:
      ACCEPT_TOKEN(sym_meta_value);
      if (lookahead == 'd') ADVANCE(154);
      if (lookahead == 'e') ADVANCE(147);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(169);
      END_STATE();
    case 139:
      ACCEPT_TOKEN(sym_meta_value);
      if (lookahead == 'd') ADVANCE(152);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(169);
      END_STATE();
    case 140:
      ACCEPT_TOKEN(sym_meta_value);
      if (lookahead == 'd') ADVANCE(153);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(169);
      END_STATE();
    case 141:
      ACCEPT_TOKEN(sym_meta_value);
      if (lookahead == 'e') ADVANCE(169);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(169);
      END_STATE();
    case 142:
      ACCEPT_TOKEN(sym_meta_value);
      if (lookahead == 'e') ADVANCE(127);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(169);
      END_STATE();
    case 143:
      ACCEPT_TOKEN(sym_meta_value);
      if (lookahead == 'e') ADVANCE(156);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(169);
      END_STATE();
    case 144:
      ACCEPT_TOKEN(sym_meta_value);
      if (lookahead == 'f') ADVANCE(145);
      if (lookahead == '+' ||
          lookahead == '-') ADVANCE(166);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(131);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(169);
      END_STATE();
    case 145:
      ACCEPT_TOKEN(sym_meta_value);
      if (lookahead == 'f') ADVANCE(155);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(169);
      END_STATE();
    case 146:
      ACCEPT_TOKEN(sym_meta_value);
      if (lookahead == 'g') ADVANCE(169);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(169);
      END_STATE();
    case 147:
      ACCEPT_TOKEN(sym_meta_value);
      if (lookahead == 'g') ADVANCE(136);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(169);
      END_STATE();
    case 148:
      ACCEPT_TOKEN(sym_meta_value);
      if (lookahead == 'i') ADVANCE(159);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(169);
      END_STATE();
    case 149:
      ACCEPT_TOKEN(sym_meta_value);
      if (lookahead == 'm') ADVANCE(169);
      if (lookahead == '+' ||
          lookahead == '-' ||
          lookahead == '=') ADVANCE(163);
      if (('a' <= lookahead && lookahead <= 'h')) ADVANCE(162);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(169);
      END_STATE();
    case 150:
      ACCEPT_TOKEN(sym_meta_value);
      if (lookahead == 'm') ADVANCE(169);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(169);
      END_STATE();
    case 151:
      ACCEPT_TOKEN(sym_meta_value);
      if (lookahead == 'p') ADVANCE(169);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(169);
      END_STATE();
    case 152:
      ACCEPT_TOKEN(sym_meta_value);
      if (lookahead == 'r') ADVANCE(158);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(169);
      END_STATE();
    case 153:
      ACCEPT_TOKEN(sym_meta_value);
      if (lookahead == 'r') ADVANCE(148);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(169);
      END_STATE();
    case 154:
      ACCEPT_TOKEN(sym_meta_value);
      if (lookahead == 's') ADVANCE(139);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(169);
      END_STATE();
    case 155:
      ACCEPT_TOKEN(sym_meta_value);
      if (lookahead == 's') ADVANCE(143);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(169);
      END_STATE();
    case 156:
      ACCEPT_TOKEN(sym_meta_value);
      if (lookahead == 't') ADVANCE(169);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(169);
      END_STATE();
    case 157:
      ACCEPT_TOKEN(sym_meta_value);
      if (lookahead == 't') ADVANCE(141);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(169);
      END_STATE();
    case 158:
      ACCEPT_TOKEN(sym_meta_value);
      if (lookahead == 'v') ADVANCE(127);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(169);
      END_STATE();
    case 159:
      ACCEPT_TOKEN(sym_meta_value);
      if (lookahead == 'v') ADVANCE(142);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(169);
      END_STATE();
    case 160:
      ACCEPT_TOKEN(sym_meta_value);
      if (lookahead == '+' ||
          lookahead == '-') ADVANCE(166);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(131);
      if (('A' <= lookahead && lookahead <= 'Z')) ADVANCE(167);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(169);
      END_STATE();
    case 161:
      ACCEPT_TOKEN(sym_meta_value);
      if (lookahead == '+' ||
          lookahead == '-') ADVANCE(166);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(131);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(169);
      END_STATE();
    case 162:
      ACCEPT_TOKEN(sym_meta_value);
      if (lookahead == '+' ||
          lookahead == '-' ||
          lookahead == '=') ADVANCE(163);
      if (('a' <= lookahead && lookahead <= 'h')) ADVANCE(162);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(169);
      END_STATE();
    case 163:
      ACCEPT_TOKEN(sym_meta_value);
      if (('a' <= lookahead && lookahead <= 'h')) ADVANCE(162);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(169);
      END_STATE();
    case 164:
      ACCEPT_TOKEN(sym_meta_value);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(165);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(165);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(169);
      END_STATE();
    case 165:
      ACCEPT_TOKEN(sym_meta_value);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(165);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(169);
      END_STATE();
    case 166:
      ACCEPT_TOKEN(sym_meta_value);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(131);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(169);
      END_STATE();
    case 167:
      ACCEPT_TOKEN(sym_meta_value);
      if (('A' <= lookahead && lookahead <= 'Z')) ADVANCE(167);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(169);
      END_STATE();
    case 168:
      ACCEPT_TOKEN(sym_meta_value);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(128);
      END_STATE();
    case 169:
      ACCEPT_TOKEN(sym_meta_value);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(169);
      END_STATE();
    case 170:
      ACCEPT_TOKEN(sym_at_command);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(170);
      END_STATE();
    case 171:
      ACCEPT_TOKEN(sym_instrument_type);
      END_STATE();
    case 172:
      ACCEPT_TOKEN(sym_note);
      if (lookahead == 'm') ADVANCE(171);
      if (lookahead == '+' ||
          lookahead == '-' ||
          lookahead == '=') ADVANCE(174);
      if (('a' <= lookahead && lookahead <= 'h')) ADVANCE(173);
      END_STATE();
    case 173:
      ACCEPT_TOKEN(sym_note);
      if (lookahead == '+' ||
          lookahead == '-' ||
          lookahead == '=') ADVANCE(174);
      if (('a' <= lookahead && lookahead <= 'h')) ADVANCE(173);
      END_STATE();
    case 174:
      ACCEPT_TOKEN(sym_note);
      if (('a' <= lookahead && lookahead <= 'h')) ADVANCE(173);
      END_STATE();
    case 175:
      ACCEPT_TOKEN(sym_rest);
      if (lookahead == 'a') ADVANCE(27);
      END_STATE();
    case 176:
      ACCEPT_TOKEN(sym_command_with_number);
      if (lookahead == '.') ADVANCE(35);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(176);
      END_STATE();
    case 177:
      ACCEPT_TOKEN(sym_command_with_number);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(177);
      END_STATE();
    case 178:
      ACCEPT_TOKEN(sym_command);
      END_STATE();
    case 179:
      ACCEPT_TOKEN(sym_command);
      if (lookahead == '_') ADVANCE(5);
      if (lookahead == '+' ||
          lookahead == '-') ADVANCE(33);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(176);
      END_STATE();
    case 180:
      ACCEPT_TOKEN(sym_command);
      if (lookahead == '_') ADVANCE(179);
      if (lookahead == '+' ||
          lookahead == '-') ADVANCE(33);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(176);
      END_STATE();
    case 181:
      ACCEPT_TOKEN(sym_command);
      if (lookahead == 'c') ADVANCE(18);
      if (lookahead == 's') ADVANCE(15);
      if (lookahead == '+' ||
          lookahead == '-') ADVANCE(33);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(176);
      END_STATE();
    case 182:
      ACCEPT_TOKEN(sym_command);
      if (lookahead == 'f') ADVANCE(13);
      if (lookahead == '+' ||
          lookahead == '-') ADVANCE(33);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(176);
      END_STATE();
    case 183:
      ACCEPT_TOKEN(sym_command);
      if (lookahead == '+' ||
          lookahead == '-') ADVANCE(33);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(176);
      END_STATE();
    case 184:
      ACCEPT_TOKEN(sym_escape_command);
      END_STATE();
    case 185:
      ACCEPT_TOKEN(sym_escape_command);
      if (lookahead == '=') ADVANCE(184);
      END_STATE();
    case 186:
      ACCEPT_TOKEN(anon_sym_SQUOTE);
      END_STATE();
    case 187:
      ACCEPT_TOKEN(anon_sym_SQUOTE);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(169);
      END_STATE();
    case 188:
      ACCEPT_TOKEN(aux_sym_platform_command_token1);
      if (lookahead == '\n') ADVANCE(190);
      if (lookahead == '\'') ADVANCE(205);
      if (lookahead != 0) ADVANCE(188);
      END_STATE();
    case 189:
      ACCEPT_TOKEN(aux_sym_platform_command_token1);
      if (lookahead == ';') ADVANCE(188);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(189);
      if (lookahead != 0 &&
          lookahead != '\'') ADVANCE(190);
      END_STATE();
    case 190:
      ACCEPT_TOKEN(aux_sym_platform_command_token1);
      if (lookahead != 0 &&
          lookahead != '\'') ADVANCE(190);
      END_STATE();
    case 191:
      ACCEPT_TOKEN(sym_platform_command_keyword);
      END_STATE();
    case 192:
      ACCEPT_TOKEN(sym_platform_command_keyword);
      if (lookahead == 'r') ADVANCE(7);
      END_STATE();
    case 193:
      ACCEPT_TOKEN(sym_number);
      if (lookahead == '.') ADVANCE(34);
      if (lookahead == 'o') ADVANCE(24);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(194);
      END_STATE();
    case 194:
      ACCEPT_TOKEN(sym_number);
      if (lookahead == '.') ADVANCE(34);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(194);
      END_STATE();
    case 195:
      ACCEPT_TOKEN(sym_number);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(195);
      END_STATE();
    case 196:
      ACCEPT_TOKEN(sym_string);
      END_STATE();
    case 197:
      ACCEPT_TOKEN(sym_track_selector);
      if (lookahead == '+' ||
          lookahead == '-') ADVANCE(33);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(176);
      if (('A' <= lookahead && lookahead <= 'Z')) ADVANCE(199);
      END_STATE();
    case 198:
      ACCEPT_TOKEN(sym_track_selector);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(198);
      END_STATE();
    case 199:
      ACCEPT_TOKEN(sym_track_selector);
      if (('A' <= lookahead && lookahead <= 'Z')) ADVANCE(199);
      END_STATE();
    case 200:
      ACCEPT_TOKEN(sym_operator);
      END_STATE();
    case 201:
      ACCEPT_TOKEN(sym_operator);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(194);
      END_STATE();
    case 202:
      ACCEPT_TOKEN(sym_operator);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(198);
      END_STATE();
    case 203:
      ACCEPT_TOKEN(sym_punctuation);
      END_STATE();
    case 204:
      ACCEPT_TOKEN(sym_param_key);
      END_STATE();
    case 205:
      ACCEPT_TOKEN(sym_comment);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(205);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexerMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 37},
  [2] = {.lex_state = 37},
  [3] = {.lex_state = 37},
  [4] = {.lex_state = 0},
  [5] = {.lex_state = 37},
  [6] = {.lex_state = 37},
  [7] = {.lex_state = 37},
  [8] = {.lex_state = 2},
  [9] = {.lex_state = 4},
  [10] = {.lex_state = 37},
  [11] = {.lex_state = 37},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [sym_meta_keyword] = ACTIONS(1),
    [sym_meta_platform_value] = ACTIONS(1),
    [sym_meta_value] = ACTIONS(1),
    [sym_at_command] = ACTIONS(1),
    [sym_instrument_type] = ACTIONS(1),
    [sym_note] = ACTIONS(1),
    [sym_rest] = ACTIONS(1),
    [sym_command_with_number] = ACTIONS(1),
    [sym_command] = ACTIONS(1),
    [sym_escape_command] = ACTIONS(1),
    [anon_sym_SQUOTE] = ACTIONS(1),
    [sym_number] = ACTIONS(1),
    [sym_string] = ACTIONS(1),
    [sym_track_selector] = ACTIONS(1),
    [sym_operator] = ACTIONS(1),
    [sym_punctuation] = ACTIONS(1),
    [sym_param_key] = ACTIONS(1),
    [sym_comment] = ACTIONS(3),
  },
  [STATE(1)] = {
    [sym_source_file] = STATE(10),
    [sym__item] = STATE(2),
    [sym_meta_command] = STATE(2),
    [sym_platform_command] = STATE(2),
    [aux_sym_source_file_repeat1] = STATE(2),
    [ts_builtin_sym_end] = ACTIONS(5),
    [sym_meta_keyword] = ACTIONS(7),
    [sym_at_command] = ACTIONS(9),
    [sym_instrument_type] = ACTIONS(9),
    [sym_note] = ACTIONS(11),
    [sym_rest] = ACTIONS(11),
    [sym_command_with_number] = ACTIONS(9),
    [sym_command] = ACTIONS(11),
    [sym_escape_command] = ACTIONS(9),
    [anon_sym_SQUOTE] = ACTIONS(13),
    [sym_number] = ACTIONS(11),
    [sym_string] = ACTIONS(9),
    [sym_track_selector] = ACTIONS(11),
    [sym_operator] = ACTIONS(11),
    [sym_punctuation] = ACTIONS(9),
    [sym_param_key] = ACTIONS(9),
    [sym_comment] = ACTIONS(15),
  },
  [STATE(2)] = {
    [sym__item] = STATE(3),
    [sym_meta_command] = STATE(3),
    [sym_platform_command] = STATE(3),
    [aux_sym_source_file_repeat1] = STATE(3),
    [ts_builtin_sym_end] = ACTIONS(17),
    [sym_meta_keyword] = ACTIONS(7),
    [sym_at_command] = ACTIONS(19),
    [sym_instrument_type] = ACTIONS(19),
    [sym_note] = ACTIONS(21),
    [sym_rest] = ACTIONS(21),
    [sym_command_with_number] = ACTIONS(19),
    [sym_command] = ACTIONS(21),
    [sym_escape_command] = ACTIONS(19),
    [anon_sym_SQUOTE] = ACTIONS(13),
    [sym_number] = ACTIONS(21),
    [sym_string] = ACTIONS(19),
    [sym_track_selector] = ACTIONS(21),
    [sym_operator] = ACTIONS(21),
    [sym_punctuation] = ACTIONS(19),
    [sym_param_key] = ACTIONS(19),
    [sym_comment] = ACTIONS(15),
  },
  [STATE(3)] = {
    [sym__item] = STATE(3),
    [sym_meta_command] = STATE(3),
    [sym_platform_command] = STATE(3),
    [aux_sym_source_file_repeat1] = STATE(3),
    [ts_builtin_sym_end] = ACTIONS(23),
    [sym_meta_keyword] = ACTIONS(25),
    [sym_at_command] = ACTIONS(28),
    [sym_instrument_type] = ACTIONS(28),
    [sym_note] = ACTIONS(31),
    [sym_rest] = ACTIONS(31),
    [sym_command_with_number] = ACTIONS(28),
    [sym_command] = ACTIONS(31),
    [sym_escape_command] = ACTIONS(28),
    [anon_sym_SQUOTE] = ACTIONS(34),
    [sym_number] = ACTIONS(31),
    [sym_string] = ACTIONS(28),
    [sym_track_selector] = ACTIONS(31),
    [sym_operator] = ACTIONS(31),
    [sym_punctuation] = ACTIONS(28),
    [sym_param_key] = ACTIONS(28),
    [sym_comment] = ACTIONS(15),
  },
  [STATE(4)] = {
    [ts_builtin_sym_end] = ACTIONS(37),
    [sym_meta_keyword] = ACTIONS(39),
    [sym_meta_platform_value] = ACTIONS(41),
    [sym_meta_value] = ACTIONS(41),
    [sym_at_command] = ACTIONS(39),
    [sym_instrument_type] = ACTIONS(39),
    [sym_note] = ACTIONS(39),
    [sym_rest] = ACTIONS(39),
    [sym_command_with_number] = ACTIONS(39),
    [sym_command] = ACTIONS(39),
    [sym_escape_command] = ACTIONS(39),
    [anon_sym_SQUOTE] = ACTIONS(39),
    [sym_number] = ACTIONS(39),
    [sym_string] = ACTIONS(39),
    [sym_track_selector] = ACTIONS(39),
    [sym_operator] = ACTIONS(39),
    [sym_punctuation] = ACTIONS(39),
    [sym_param_key] = ACTIONS(39),
    [sym_comment] = ACTIONS(3),
  },
  [STATE(5)] = {
    [ts_builtin_sym_end] = ACTIONS(43),
    [sym_meta_keyword] = ACTIONS(43),
    [sym_at_command] = ACTIONS(43),
    [sym_instrument_type] = ACTIONS(43),
    [sym_note] = ACTIONS(45),
    [sym_rest] = ACTIONS(45),
    [sym_command_with_number] = ACTIONS(43),
    [sym_command] = ACTIONS(45),
    [sym_escape_command] = ACTIONS(43),
    [anon_sym_SQUOTE] = ACTIONS(43),
    [sym_number] = ACTIONS(45),
    [sym_string] = ACTIONS(43),
    [sym_track_selector] = ACTIONS(45),
    [sym_operator] = ACTIONS(45),
    [sym_punctuation] = ACTIONS(43),
    [sym_param_key] = ACTIONS(43),
    [sym_comment] = ACTIONS(15),
  },
  [STATE(6)] = {
    [ts_builtin_sym_end] = ACTIONS(47),
    [sym_meta_keyword] = ACTIONS(47),
    [sym_at_command] = ACTIONS(47),
    [sym_instrument_type] = ACTIONS(47),
    [sym_note] = ACTIONS(49),
    [sym_rest] = ACTIONS(49),
    [sym_command_with_number] = ACTIONS(47),
    [sym_command] = ACTIONS(49),
    [sym_escape_command] = ACTIONS(47),
    [anon_sym_SQUOTE] = ACTIONS(47),
    [sym_number] = ACTIONS(49),
    [sym_string] = ACTIONS(47),
    [sym_track_selector] = ACTIONS(49),
    [sym_operator] = ACTIONS(49),
    [sym_punctuation] = ACTIONS(47),
    [sym_param_key] = ACTIONS(47),
    [sym_comment] = ACTIONS(15),
  },
  [STATE(7)] = {
    [ts_builtin_sym_end] = ACTIONS(51),
    [sym_meta_keyword] = ACTIONS(51),
    [sym_at_command] = ACTIONS(51),
    [sym_instrument_type] = ACTIONS(51),
    [sym_note] = ACTIONS(53),
    [sym_rest] = ACTIONS(53),
    [sym_command_with_number] = ACTIONS(51),
    [sym_command] = ACTIONS(53),
    [sym_escape_command] = ACTIONS(51),
    [anon_sym_SQUOTE] = ACTIONS(51),
    [sym_number] = ACTIONS(53),
    [sym_string] = ACTIONS(51),
    [sym_track_selector] = ACTIONS(53),
    [sym_operator] = ACTIONS(53),
    [sym_punctuation] = ACTIONS(51),
    [sym_param_key] = ACTIONS(51),
    [sym_comment] = ACTIONS(15),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(55), 1,
      anon_sym_SQUOTE,
    ACTIONS(57), 1,
      aux_sym_platform_command_token1,
  [10] = 2,
    ACTIONS(15), 1,
      sym_comment,
    ACTIONS(59), 1,
      sym_platform_command_keyword,
  [17] = 2,
    ACTIONS(15), 1,
      sym_comment,
    ACTIONS(61), 1,
      ts_builtin_sym_end,
  [24] = 2,
    ACTIONS(15), 1,
      sym_comment,
    ACTIONS(63), 1,
      anon_sym_SQUOTE,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(8)] = 0,
  [SMALL_STATE(9)] = 10,
  [SMALL_STATE(10)] = 17,
  [SMALL_STATE(11)] = 24,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = false}}, SHIFT_EXTRA(),
  [5] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 0, 0, 0),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(4),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(2),
  [11] = {.entry = {.count = 1, .reusable = false}}, SHIFT(2),
  [13] = {.entry = {.count = 1, .reusable = true}}, SHIFT(9),
  [15] = {.entry = {.count = 1, .reusable = true}}, SHIFT_EXTRA(),
  [17] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1, 0, 0),
  [19] = {.entry = {.count = 1, .reusable = true}}, SHIFT(3),
  [21] = {.entry = {.count = 1, .reusable = false}}, SHIFT(3),
  [23] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0),
  [25] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(4),
  [28] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(3),
  [31] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(3),
  [34] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(9),
  [37] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_meta_command, 1, 0, 0),
  [39] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_meta_command, 1, 0, 0),
  [41] = {.entry = {.count = 1, .reusable = false}}, SHIFT(5),
  [43] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_meta_command, 2, 0, 0),
  [45] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_meta_command, 2, 0, 0),
  [47] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_platform_command, 3, 0, 1),
  [49] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_platform_command, 3, 0, 1),
  [51] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_platform_command, 4, 0, 2),
  [53] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_platform_command, 4, 0, 2),
  [55] = {.entry = {.count = 1, .reusable = false}}, SHIFT(6),
  [57] = {.entry = {.count = 1, .reusable = false}}, SHIFT(11),
  [59] = {.entry = {.count = 1, .reusable = true}}, SHIFT(8),
  [61] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [63] = {.entry = {.count = 1, .reusable = true}}, SHIFT(7),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_ctrmml(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .supertype_count = SUPERTYPE_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .field_names = ts_field_names,
    .field_map_slices = ts_field_map_slices,
    .field_map_entries = ts_field_map_entries,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
    .name = "ctrmml",
    .max_reserved_word_set_size = 0,
    .metadata = {
      .major_version = 0,
      .minor_version = 0,
      .patch_version = 9,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
